apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecommerce-app
  template:
    metadata:
      labels:
        app: ecommerce-app
    spec:
      containers:
        - name: ecommerce-app
          image: azizshaikh/ecommerce-app
          ports:
            - containerPort: 8080
          env:
            - configMapRef:
                name: ecommerce-db-config
            - secretRef:
                name: ecommerce-secret
